# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockpose < Formula
  desc "A keyboard-driven TUI for managing Docker Compose stacks."
  homepage "https://github.com/cwklurks/dockpose"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cwklurks/dockpose/releases/download/v0.1.6/dockpose_0.1.6_Darwin_x86_64.tar.gz"
      sha256 "6d08547e22af0be227dd00d1ad908f6a70c4b2ac4743d51de59846975966a7d2"

      define_method(:install) do
        bin.install "dockpose"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cwklurks/dockpose/releases/download/v0.1.6/dockpose_0.1.6_Darwin_arm64.tar.gz"
      sha256 "e64dddb11607dcdbf9781d38f6d65a6d0b764b0e2d59ca1c634f0e99d3fc6a2b"

      define_method(:install) do
        bin.install "dockpose"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cwklurks/dockpose/releases/download/v0.1.6/dockpose_0.1.6_Linux_x86_64.tar.gz"
      sha256 "96e1fff7cb3ed2fb569038078e733ae5bef8817910ac8161519dcb231126cb25"
      define_method(:install) do
        bin.install "dockpose"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cwklurks/dockpose/releases/download/v0.1.6/dockpose_0.1.6_Linux_arm64.tar.gz"
      sha256 "9f807ffbf7304895bdd01d05de3b32e15bbc7068ea59b27c842da6b7e9f2979b"
      define_method(:install) do
        bin.install "dockpose"
      end
    end
  end

  test do
    system "#{bin}/dockpose", "--version"
  end
end
