# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockpose < Formula
  desc "A keyboard-driven TUI for managing Docker Compose stacks."
  homepage "https://github.com/cwklurks/dockpose"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cwklurks/dockpose/releases/download/v0.2.1/dockpose_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "968464f00a4de2a63f1542872ca5d598d05b5b8ba217692e5e11adcc09dd46fa"

      define_method(:install) do
        bin.install "dockpose"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cwklurks/dockpose/releases/download/v0.2.1/dockpose_0.2.1_Darwin_arm64.tar.gz"
      sha256 "a8026e3d25218ab14376a82897b54d2c78c5b2c5e51853b7a9ee4d82127f00b6"

      define_method(:install) do
        bin.install "dockpose"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cwklurks/dockpose/releases/download/v0.2.1/dockpose_0.2.1_Linux_x86_64.tar.gz"
      sha256 "09e620466df19d53ac3d833b5d257eeeb98e715698672fb6d7f7d75ee14f464b"
      define_method(:install) do
        bin.install "dockpose"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cwklurks/dockpose/releases/download/v0.2.1/dockpose_0.2.1_Linux_arm64.tar.gz"
      sha256 "2123c1f6b8e77b91d39a84ce7bf9bdb72c3e9bfc399417ec78b1950af6ca73a3"
      define_method(:install) do
        bin.install "dockpose"
      end
    end
  end

  test do
    system "#{bin}/dockpose", "--version"
  end
end
